name: "Felpojam Export Script" 
on:
  push:
    branches:
    - main
    paths:
    - 'source/**'
    - '.github/workflows/build.yaml'

env:
  GODOT_VERSION: 4.6.0
  USER_VERSION: "1.0.${{ github.run_number }}"

jobs:
  build-desktop-clients:
    name: Export Game Binaries
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [windows, linux]
        bin-name: [krimbo.exe, krimbo.x86_64]
    steps:
      - uses: actions/checkout@v4
        name: Checkout
      
      - uses: chickensoft-games/setup-godot@v2
        name: Setup Godot
        with:
          version: ${{ env.GODOT_VERSION }}
          use-dotnet: false
          include-templates: true

      - name: Prepare directory
        run: mkdir -p compiled/${{ matrix.target }}

      - name: Export ${{ matrix.target }} release
        run: godot --headless --path ./source/ --export-release ${{ matrix.target }} ../compiled/${{ matrix.target }}/${{ matrix.bin-name }}

      - uses: XanatosX/butler-publish-itchio-action@master
        name: Publish Windows Version
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: ${{ matrix.target }}
          ITCH_GAME: ruinas-de-krimbo
          ITCH_USER: lazaromenezes
          PACKAGE: compiled/windows
          VERSION: ${{ env.USER_VERSION }}
